apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-1
  template:
    metadata:
      labels:
        app: storage-node-1
    spec:
      containers:
      - name: storage-node-1
        image: your-dockerhub/storage-node-1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-1
spec:
  selector:
    app: storage-node-1
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: NodePort
